eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

server:
  port: 8222

spring:
  application:
    name: gateway  # Name of the Spring Boot application
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true  # Enable discovery locator for Gateway
      routes:
        - id: students
          uri: http://localhost:8090  # The URI for the 'students' service
          predicates:
            - Path=/api/v1/students/**  # Routing path for 'students' service
        - id: schools
          uri: http://localhost:8070  # The URI for the 'schools' service
          predicates:
            - Path=/api/v1/schools/**  # Routing path for 'schools' service
